# Building the feeder step by step

This notebook reads `data/sample/kt1_sample.csv` (built by `sampler_dev.ipynb`) and drips it into `data/stream_input/` as small files over time — simulating events arriving live for `streaming_job_dev.ipynb` to consume.

Run `streaming_job_dev.ipynb` first (or side by side) so a consumer is ready when files start landing.

In [1]:
import sys
sys.path.insert(0, "../src")

import os
import shutil
import time
from pathlib import Path

import pandas as pd
from config import (
    SAMPLE_FILE,
    STREAM_INPUT_DIR,
    CHECKPOINT_DIR,
    KT1_STREAM_COLUMNS,
    DEFAULT_BATCH_ROWS,
    DEFAULT_FEED_INTERVAL_SEC,
)

pd.set_option("display.max_columns", None)

In [2]:
DTYPES = {
    "timestamp": "int64",
    "solving_id": "int64",
    "question_id": "string",
    "user_answer": "string",
    "elapsed_time": "int64",
    "user_id": "string",
}

sample = pd.read_csv(SAMPLE_FILE, dtype=DTYPES)
print(sample.shape)
sample.head()

(43574, 6)

       timestamp  solving_id question_id user_answer  elapsed_time user_id
0  1498906740412           1        q129           b         27000  u22094
1  1498906764080           2       q8058           b         22000  u22094
2  1498906786376           3       q8120           a         20000  u22094
3  1498906818824           4        q157           d         30000  u22094
4  1498906848124           5         q52           b         27000  u22094

## Step 1 — split the sample into ordered row-chunks

We need to slice `sample` into consecutive pieces of `batch_rows` rows each — **preserving the timestamp order** the sampler already sorted (don't shuffle). Each chunk becomes one file that lands in `data/stream_input/` later.

Fill in the two blanks: `range(start, stop, step)` needs a step size, and each slice needs an end position. Both should be `batch_rows`.

In [3]:
def chunk_dataframe(df: pd.DataFrame, batch_rows: int):
    for start in range(0, len(df), batch_rows):  # TODO: fill in
        yield df.iloc[start : start + batch_rows]  # TODO: fill in


chunks = list(chunk_dataframe(sample, DEFAULT_BATCH_ROWS))
print(len(chunks), "chunks")
print("first chunk:", chunks[0].shape, "last chunk:", chunks[-1].shape)

218 chunks
first chunk: (200, 6) last chunk: (174, 6)

## Step 2 — write one chunk to disk, atomically

Spark's streaming file source polls `data/stream_input/` and could read a file while it's still being written, if we write directly to the final filename. The fix: write to a hidden temp name first, then atomically rename it to the real name. Spark's directory listing never sees a half-written file this way (and files starting with `.` are ignored by Spark's file source anyway, as a backup safety net).

Fill in the three blanks:
1. Which path should `chunk.to_csv(...)` write to — the temp path or the final path?
2. `os.replace(src, dst)` renames `src` to `dst`. Which is which here?"

In [4]:
def write_batch(chunk: pd.DataFrame, seq: int, out_dir: Path) -> Path:
    final_path = out_dir / f"part-{seq:06d}.csv"
    tmp_path = out_dir / f".tmp-part-{seq:06d}.csv"

    chunk.to_csv(tmp_path, index=False)  # TODO: write to which path first?
    os.replace(tmp_path, final_path)            # TODO: rename which path to which?

    return final_path


STREAM_INPUT_DIR.mkdir(parents=True, exist_ok=True)
test_path = write_batch(chunks[0], 0, STREAM_INPUT_DIR)
print(test_path, test_path.exists())
pd.read_csv(test_path, dtype=DTYPES).head()

/home/verseua/projects/PySpark-Data-Processing/data/stream_input/part-000000.csv True

       timestamp  solving_id question_id user_answer  elapsed_time user_id
0  1498906740412           1        q129           b         27000  u22094
1  1498906764080           2       q8058           b         22000  u22094
2  1498906786376           3       q8120           a         20000  u22094
3  1498906818824           4        q157           d         30000  u22094
4  1498906848124           5         q52           b         27000  u22094

## Step 3 — reset between demo runs

Between runs we want a clean slate: delete leftover `.csv` files in `data/stream_input/`, **and** delete Spark's checkpoint directories. Reason: a checkpoint remembers which files were already processed — if you wipe the input files but leave an old checkpoint around, a fresh run can get confusing offset bookkeeping. Clearing both together keeps every run reproducible.

Fill in the one blank: which `shutil` function deletes an entire directory tree (not just a single file)?

In [5]:
def reset_dir(out_dir: Path, checkpoint_dir: Path) -> None:
    csv_files = list(out_dir.glob("*.csv"))
    print(f"Deleting {len(csv_files)} existing files in {out_dir}")
    for f in csv_files:
        f.unlink()

    if checkpoint_dir.exists():
        print(f"Deleting checkpoint dir {checkpoint_dir}")
        shutil.rmtree(checkpoint_dir)  # TODO: which shutil function?
        checkpoint_dir.mkdir(parents=True, exist_ok=True)

## Step 4 — run the feed loop

Puts it all together: reset, then write one chunk at a time with a pause in between, so files trickle into `data/stream_input/` like a live feed.

Make sure `streaming_job_dev.ipynb` is already running before you run this cell, so it's watching the directory as files land.

Fill in the four blanks: the three arguments `write_batch` needs (which chunk, which sequence number, which output directory), and which config constant controls how long to pause between batches.

This cell blocks while it runs — use the notebook's interrupt/stop button to stop early if you want; already-written files stay in place."

In [6]:
reset_dir(STREAM_INPUT_DIR, CHECKPOINT_DIR)

all_chunks = list(chunk_dataframe(sample, DEFAULT_BATCH_ROWS))
total = len(all_chunks)

for seq, chunk in enumerate(all_chunks):
    path = write_batch(chunk, seq, STREAM_INPUT_DIR)  # TODO: fill in the three args
    print(f"wrote {path.name} ({len(chunk)} rows) — {seq + 1}/{total}")
    time.sleep(DEFAULT_FEED_INTERVAL_SEC)  # TODO: which config constant?

Deleting 34 existing files in /home/verseua/projects/PySpark-Data-Processing/data/stream_input
Deleting checkpoint dir /home/verseua/projects/PySpark-Data-Processing/checkpoints
wrote part-000000.csv (200 rows) — 1/218

wrote part-000001.csv (200 rows) — 2/218
wrote part-000002.csv (200 rows) — 3/218
wrote part-000003.csv (200 rows) — 4/218
wrote part-000004.csv (200 rows) — 5/218
wrote part-000005.csv (200 rows) — 6/218
wrote part-000006.csv (200 rows) — 7/218
wrote part-000007.csv (200 rows) — 8/218
wrote part-000008.csv (200 rows) — 9/218
wrote part-000009.csv (200 rows) — 10/218
wrote part-000010.csv (200 rows) — 11/218
wrote part-000011.csv (200 rows) — 12/218
wrote part-000012.csv (200 rows) — 13/218
wrote part-000013.csv (200 rows) — 14/218
wrote part-000014.csv (200 rows) — 15/218
wrote part-000015.csv (200 rows) — 16/218
wrote part-000016.csv (200 rows) — 17/218
wrote part-000017.csv (200 rows) — 18/218
wrote part-000018.csv (200 rows) — 19/218
wrote part-000019.csv (200 rows) — 20/218
wrote part-000020.csv (200 rows) — 21/218
wrote part-000021.csv (200 rows) — 22/218
wrote part-000022.csv (200 rows) — 23/218
wrote part-000023.csv (200 rows) — 24/218
wrote part-000024.csv (200 rows) — 25/218
wrote part-000025.csv (200 rows) — 26/218
wrote part-000026.csv (200 rows) — 27/218
wrote part-000027.csv (200 rows) — 28/218
wrote part-000028.csv (200 rows) — 29/218
wrote part-000029.csv (200 rows) — 30/218
wrote part-000030.csv (200 rows) — 31/218
wrote part-000031.csv (200 rows) — 32/218
wrote part-000032.csv (200 rows) — 33/218
wrote part-000033.csv (200 rows) — 34/218
wrote part-000034.csv (200 rows) — 35/218
wrote part-000035.csv (200 rows) — 36/218
wrote part-000036.csv (200 rows) — 37/218
wrote part-000037.csv (200 rows) — 38/218
wrote part-000038.csv (200 rows) — 39/218
wrote part-000039.csv (200 rows) — 40/218
wrote part-000040.csv (200 rows) — 41/218
wrote part-000041.csv (200 rows) — 42/218
wrote part-000042.csv (200 rows) — 43/218
wrote part-000043.csv (200 rows) — 44/218
wrote part-000044.csv (200 rows) — 45/218
wrote part-000045.csv (200 rows) — 46/218
wrote part-000046.csv (200 rows) — 47/218
wrote part-000047.csv (200 rows) — 48/218
wrote part-000048.csv (200 rows) — 49/218
wrote part-000049.csv (200 rows) — 50/218
wrote part-000050.csv (200 rows) — 51/218
wrote part-000051.csv (200 rows) — 52/218
wrote part-000052.csv (200 rows) — 53/218
wrote part-000053.csv (200 rows) — 54/218
wrote part-000054.csv (200 rows) — 55/218
wrote part-000055.csv (200 rows) — 56/218
wrote part-000056.csv (200 rows) — 57/218
wrote part-000057.csv (200 rows) — 58/218
wrote part-000058.csv (200 rows) — 59/218
wrote part-000059.csv (200 rows) — 60/218
wrote part-000060.csv (200 rows) — 61/218
wrote part-000061.csv (200 rows) — 62/218
wrote part-000062.csv (200 rows) — 63/218
wrote part-000063.csv (200 rows) — 64/218
wrote part-000064.csv (200 rows) — 65/218
wrote part-000065.csv (200 rows) — 66/218
wrote part-000066.csv (200 rows) — 67/218
wrote part-000067.csv (200 rows) — 68/218
wrote part-000068.csv (200 rows) — 69/218
wrote part-000069.csv (200 rows) — 70/218
wrote part-000070.csv (200 rows) — 71/218
wrote part-000071.csv (200 rows) — 72/218
wrote part-000072.csv (200 rows) — 73/218
wrote part-000073.csv (200 rows) — 74/218
wrote part-000074.csv (200 rows) — 75/218
wrote part-000075.csv (200 rows) — 76/218
wrote part-000076.csv (200 rows) — 77/218
wrote part-000077.csv (200 rows) — 78/218
wrote part-000078.csv (200 rows) — 79/218
wrote part-000079.csv (200 rows) — 80/218
wrote part-000080.csv (200 rows) — 81/218
wrote part-000081.csv (200 rows) — 82/218
wrote part-000082.csv (200 rows) — 83/218
wrote part-000083.csv (200 rows) — 84/218
wrote part-000084.csv (200 rows) — 85/218
wrote part-000085.csv (200 rows) — 86/218
wrote part-000086.csv (200 rows) — 87/218
wrote part-000087.csv (200 rows) — 88/218
wrote part-000088.csv (200 rows) — 89/218
wrote part-000089.csv (200 rows) — 90/218
wrote part-000090.csv (200 rows) — 91/218
wrote part-000091.csv (200 rows) — 92/218
wrote part-000092.csv (200 rows) — 93/218
wrote part-000093.csv (200 rows) — 94/218
wrote part-000094.csv (200 rows) — 95/218
wrote part-000095.csv (200 rows) — 96/218
wrote part-000096.csv (200 rows) — 97/218
wrote part-000097.csv (200 rows) — 98/218
wrote part-000098.csv (200 rows) — 99/218
wrote part-000099.csv (200 rows) — 100/218
wrote part-000100.csv (200 rows) — 101/218
wrote part-000101.csv (200 rows) — 102/218
wrote part-000102.csv (200 rows) — 103/218
wrote part-000103.csv (200 rows) — 104/218
wrote part-000104.csv (200 rows) — 105/218
wrote part-000105.csv (200 rows) — 106/218
wrote part-000106.csv (200 rows) — 107/218
wrote part-000107.csv (200 rows) — 108/218
wrote part-000108.csv (200 rows) — 109/218
wrote part-000109.csv (200 rows) — 110/218
wrote part-000110.csv (200 rows) — 111/218
wrote part-000111.csv (200 rows) — 112/218
wrote part-000112.csv (200 rows) — 113/218
wrote part-000113.csv (200 rows) — 114/218
wrote part-000114.csv (200 rows) — 115/218
wrote part-000115.csv (200 rows) — 116/218
wrote part-000116.csv (200 rows) — 117/218
wrote part-000117.csv (200 rows) — 118/218
wrote part-000118.csv (200 rows) — 119/218
wrote part-000119.csv (200 rows) — 120/218
wrote part-000120.csv (200 rows) — 121/218
wrote part-000121.csv (200 rows) — 122/218
wrote part-000122.csv (200 rows) — 123/218
wrote part-000123.csv (200 rows) — 124/218
wrote part-000124.csv (200 rows) — 125/218
wrote part-000125.csv (200 rows) — 126/218
wrote part-000126.csv (200 rows) — 127/218
wrote part-000127.csv (200 rows) — 128/218
wrote part-000128.csv (200 rows) — 129/218
wrote part-000129.csv (200 rows) — 130/218
wrote part-000130.csv (200 rows) — 131/218
wrote part-000131.csv (200 rows) — 132/218
wrote part-000132.csv (200 rows) — 133/218
wrote part-000133.csv (200 rows) — 134/218
wrote part-000134.csv (200 rows) — 135/218
wrote part-000135.csv (200 rows) — 136/218
wrote part-000136.csv (200 rows) — 137/218
wrote part-000137.csv (200 rows) — 138/218
wrote part-000138.csv (200 rows) — 139/218
wrote part-000139.csv (200 rows) — 140/218
wrote part-000140.csv (200 rows) — 141/218
wrote part-000141.csv (200 rows) — 142/218
wrote part-000142.csv (200 rows) — 143/218
wrote part-000143.csv (200 rows) — 144/218
wrote part-000144.csv (200 rows) — 145/218
wrote part-000145.csv (200 rows) — 146/218
wrote part-000146.csv (200 rows) — 147/218
wrote part-000147.csv (200 rows) — 148/218
wrote part-000148.csv (200 rows) — 149/218
wrote part-000149.csv (200 rows) — 150/218
wrote part-000150.csv (200 rows) — 151/218
wrote part-000151.csv (200 rows) — 152/218
wrote part-000152.csv (200 rows) — 153/218
wrote part-000153.csv (200 rows) — 154/218
wrote part-000154.csv (200 rows) — 155/218
wrote part-000155.csv (200 rows) — 156/218
wrote part-000156.csv (200 rows) — 157/218
wrote part-000157.csv (200 rows) — 158/218
wrote part-000158.csv (200 rows) — 159/218
wrote part-000159.csv (200 rows) — 160/218
wrote part-000160.csv (200 rows) — 161/218
wrote part-000161.csv (200 rows) — 162/218
wrote part-000162.csv (200 rows) — 163/218
wrote part-000163.csv (200 rows) — 164/218
wrote part-000164.csv (200 rows) — 165/218
wrote part-000165.csv (200 rows) — 166/218
wrote part-000166.csv (200 rows) — 167/218
wrote part-000167.csv (200 rows) — 168/218
wrote part-000168.csv (200 rows) — 169/218
wrote part-000169.csv (200 rows) — 170/218
wrote part-000170.csv (200 rows) — 171/218
wrote part-000171.csv (200 rows) — 172/218
wrote part-000172.csv (200 rows) — 173/218
wrote part-000173.csv (200 rows) — 174/218
wrote part-000174.csv (200 rows) — 175/218
wrote part-000175.csv (200 rows) — 176/218
wrote part-000176.csv (200 rows) — 177/218
wrote part-000177.csv (200 rows) — 178/218
wrote part-000178.csv (200 rows) — 179/218
wrote part-000179.csv (200 rows) — 180/218
wrote part-000180.csv (200 rows) — 181/218
wrote part-000181.csv (200 rows) — 182/218
wrote part-000182.csv (200 rows) — 183/218
wrote part-000183.csv (200 rows) — 184/218
wrote part-000184.csv (200 rows) — 185/218
wrote part-000185.csv (200 rows) — 186/218
wrote part-000186.csv (200 rows) — 187/218
wrote part-000187.csv (200 rows) — 188/218
wrote part-000188.csv (200 rows) — 189/218
wrote part-000189.csv (200 rows) — 190/218
wrote part-000190.csv (200 rows) — 191/218
wrote part-000191.csv (200 rows) — 192/218
wrote part-000192.csv (200 rows) — 193/218
wrote part-000193.csv (200 rows) — 194/218
wrote part-000194.csv (200 rows) — 195/218
wrote part-000195.csv (200 rows) — 196/218
wrote part-000196.csv (200 rows) — 197/218
wrote part-000197.csv (200 rows) — 198/218
wrote part-000198.csv (200 rows) — 199/218
wrote part-000199.csv (200 rows) — 200/218
wrote part-000200.csv (200 rows) — 201/218
wrote part-000201.csv (200 rows) — 202/218
wrote part-000202.csv (200 rows) — 203/218
wrote part-000203.csv (200 rows) — 204/218
wrote part-000204.csv (200 rows) — 205/218
wrote part-000205.csv (200 rows) — 206/218
wrote part-000206.csv (200 rows) — 207/218
wrote part-000207.csv (200 rows) — 208/218
wrote part-000208.csv (200 rows) — 209/218
wrote part-000209.csv (200 rows) — 210/218
wrote part-000210.csv (200 rows) — 211/218
wrote part-000211.csv (200 rows) — 212/218
wrote part-000212.csv (200 rows) — 213/218
wrote part-000213.csv (200 rows) — 214/218
wrote part-000214.csv (200 rows) — 215/218
wrote part-000215.csv (200 rows) — 216/218
wrote part-000216.csv (200 rows) — 217/218
wrote part-000217.csv (174 rows) — 218/218